-- Create notes table
CREATE TABLE IF NOT EXISTS notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null default '',
  content text not null default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable RLS
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

-- Policy: users can only access their own notes
CREATE POLICY "Users can manage own notes" ON notes
  FOR ALL USING (auth.uid() = user_id);
